version: "3.7"

services:
  app:
    build: .
    image: railway-game-img
    container_name: railway-game
    restart: unless-stopped
    env_file:
      - .env
  redis:
    image: redis:alpine
    container_name: railway-game-redis
    restart: unless-stopped
networks:
  default:
    name: nginx
    external: true