export enum SETTINGS_KEY {
  BRIDGE_CONSTRUCTION_TIME = "BRIDGE_CONSTRUCTION_TIME",
  RAIL_ROAD_CONSTRUCTION_TIME = "RAIL_ROAD_CONSTRUCTION_TIME",
  NFT_LOCK_TIME = "NFT_LOCK_TIME",
  RAIL_MOVEMENT_LOCK_TIME = "RAIL_MOVEMENT_LOCK_TIME",
  LIGHT_NFT_LOCKING_TIME = "LIGHT_NFT_LOCKING_TIME",
}
